### PR TITLE
Viewer update

### PR DESCRIPTION
**Pull request by anthoak13**
Here are my changes. I'm going to work on getting pattern events drawn tomorrow, but I can merge that with what you are doing. I don't think what you are doing is going to mess with the AtTabMain class much at all so I don't think both of us working on the visualizer at the same time will be much of a problem. I also sketched out an interface for the sidebar but didn't move anything over there that needed to use the observer/subject stuff. I also added the code version of what we sketched for the PSA subject/observer and moved the classes around into more intuitive spots. I tried to leave git commit messages that explained why I did what I did.

### CODE REVIEW

**Comment by anthoak13** [comment]
Worth noting here is the test macro https://github.com/anthoak13/ATTPCROOTv2/blob/viewerUpdate/macro/e12014/viewerUpdate/run_eve_test_multi.C

It pulls data from /mnt/analysis.

**Comment by anthoak13** [comment]
A thought I had that I'm too tired to do tonight:

Make AtEventSidebar a singleton. Then AtSidebarFrames can poll that to figure out their parent in their constructors, and we can remove the confusing function AddSidebarFrame, and just overload AddFrame to check if the added frame is a AtSidebarFrame and add it to the vector if it is. Then just pass the frame onto TGMainFrame::AddFrame(). Then you can drop all the enum crap and it will make maintance easier as well.

**Comment by anthoak13** [comment]
Oh also I'd do a rebase or merge, not a squash when pulling the changes in. I think we'll want the commit log intact until we're ready to merge into the main branch

**Comment by cnhunt** [comment]
comment

**Pull request merged**
